spring.application.name=biblia
spring.datasource.url=jdbc:postgresql://localhost:5432/biblia_db
spring.datasource.username=sloa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8081
spring.jpa.open-in-view=false